# Generated by Django 5.1.2 on 2024-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('w', 'working'), ('d', 'Done')], default='p', max_length=100),
        ),
    ]
